### ISSUE TITLE
Could not connect with server

### ISSUE THREAD

**Issue by FinleyVickers** [imRohan/ubersicht-morning.widget#5]
The widget is not loading with the error Failed to load resource: Could not connect to the server. With the URL http://127.0.0.1:41416/69680128

**Comment by imRohan** [comment]
That's interesting. I'm not entirely sure if this error was thrown by the Morning widget or Ubersicht, ill look into it.

The Morning widget does not spawn a server locally, and more importantly, does not load any external assets so im not sure what's trying to connect to a server.

Are you running any other widgets?

**Comment by FinleyVickers** [comment]
I am not, though I tried to run other widgets after and was getting the same error (sorry for late reply)

**Comment by imRohan** [comment]
No problem. 

This may be an issue with Ubersicht, and not the widget. Going to close this issue for now. However, I am curious if you have some sort of anti-virus or firewall that is interfering?
