### ISSUE TITLE
Yellow background behind the text.

### ISSUE THREAD

**Issue by aravezskinteeth** [imRohan/ubersicht-morning.widget#6]
# Description of the problem
OS: MacOS BigSur 11.4

I downloaded your widget, it works but there's a yellow background behind the text, like this:

<img width="1280" alt="Screen Shot 2022-12-14 at 3 03 14 PM" src="https://user-images.githubusercontent.com/104392087/207709045-e0634e80-7982-4081-ac2a-61318a52d4ab.png">

I tried to edit the coffee script, but I don't know exactly, where the issue lies.

**Comment by imRohan** [comment]
@aravezskinteeth This is an odd one. There should not be any background applied to the widget, let alone a yellow one.

Im curious if there is a conflict between Morning and another widget that you have currently running on your machine. What happens if you only run Morning? 

The issue would lie in the [css of `.container`](https://github.com/imRohan/ubersicht-morning.widget/blob/4cf832af1825a3a98d649f21b547e336c624ef79/morning.widget/morning.coffee#L21)

**Comment by aravezskinteeth** [comment]
I disabled my simple bar widget but the problem persists

<img width="1280" alt="Screen Shot 2022-12-14 at 4 03 14 PM" src="https://user-images.githubusercontent.com/104392087/207714381-6ce38cac-a058-4e8c-819c-828dace128ef.png">

I even deleted it from the widgets folder

<img width="737" alt="Screen Shot 2022-12-14 at 4 03 33 PM" src="https://user-images.githubusercontent.com/104392087/207714623-2dda2700-bcf9-47f1-948b-467e88d5d3b7.png">

Is there any property I can add or modify in `.containers`? I don't know much css I'm afraid.

**Comment by imRohan** [comment]
@aravezskinteeth Ok interesting.

There are two places you can try modifying, under `.container` and `.time`.

Please add the following line `background-color: rgba(0,0,0,0) !important`.

This will force a black background with 0% opacity, and should override any other rules currently in place.

**Comment by aravezskinteeth** [comment]
Turns out I had to quit Übersicht to see the changes first after deleting the other widgets. Upon inspection, I could see that the widget [Simple bar](https://github.com/Jean-Tinland/simple-bar) was the culprit. 

![image](https://user-images.githubusercontent.com/104392087/207719444-74269460-d371-4d0b-8511-cb9cd5e9f71b.png)

**Comment by imRohan** [comment]
@aravezskinteeth Ok, that makes sense, I'm guessing both widgets share the same css class name `.time`. If you'd like, just find and replace `.time` in morning-widget to something else such as `.morning-time`.

That way you can run both widgets and they won't conflict.

**Comment by aravezskinteeth** [comment]
I replaced `.time` with `.morning-time` and quit Übersicht but it looks like this now

![image](https://user-images.githubusercontent.com/104392087/207721379-4d72bcb4-030f-4db1-96ec-9964da1088e4.jpeg)

**Comment by imRohan** [comment]
@aravezskinteeth You also have to change 'time' to 'morning-time' on [this line](https://github.com/imRohan/ubersicht-morning.widget/blob/4cf832af1825a3a98d649f21b547e336c624ef79/morning.widget/morning.coffee#L64)

**Comment by aravezskinteeth** [comment]
Oops ok just fixed it. Thank you so much for taking your time and help me with this.

![image](https://user-images.githubusercontent.com/104392087/207722680-f4b08d7c-df09-4d7b-878f-698b7eed3530.jpeg)

**Comment by imRohan** [comment]
@aravezskinteeth No problem! Hope you enjoy the widget :)
